FidehJobs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views


urlpatterns = [
    path('admin/for-management/of/this/domain/', admin.site.urls,name="management"),
    path('', include('apps.core.urls')),
    path('job/',include('apps.job.urls')),
    path('user/', include('apps.users.urls')),
    path('notification',include('apps.notification.urls')),
    path('accounts/password_reset/',views.PasswordResetView.as_view(template_name="password/password_reset.html"),name='password_reset'),
    path('user/password/reset/done/',views.PasswordResetDoneView.as_view(template_name="password/password_reset_done.html"),name='password_reset_done'),
    path('user/<uidb64>/password/<token>/confirm/',views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"),name='password_reset_confirm'),
    path('user/password/reset/success/',views.PasswordResetCompleteView.as_view(template_name="password/password_reset_complete.html"),name='password_reset_complete'),

    
]

apps/job/urls.py
from django.urls import path 
from .views import JobList, JobDetail,JobCreate,JobApplication,JobEdit,JobDelete,ApplicationDelete,JobSearch

app_name = 'job'
urlpatterns =[
    path('fideht/job<int:pk>/',JobDetail.as_view(),name='job-detail'),
    path('fideht/jobs/',JobList.as_view(),name='job-list'),
    path('fideht/job/create/',JobCreate.as_view(),name='create-job'),
    path('fideht/job/edit/<int:pk>/',JobEdit.as_view(),name='edit-job'),
    path('fideh/jobs/delete/<int:pk>/',JobDelete.as_view(),name='delete-job'),
    path('fideht/jobs/job<int:pk>/apply/',JobApplication.as_view(),name='job-apply'),
    path('fideht/job/application/<int:pk>/delete/',ApplicationDelete.as_view(),name='application-delete'),
    path('fideht/jobs/search/',JobSearch.as_view(),name='search'),
]

apps/users/urls.py
from django.urls import path
from .views import Dashboard, EmployerJobDetail, ApplicantJobDetail,ProfileView,ProfileEditView

app_name = 'users'
urlpatterns =[
    path('dashboard/',Dashboard.as_view(),name='dashboard'),
    path('dashboard/applicant/application<int:pk>/',ApplicantJobDetail.as_view(),name='applicant-detail'),
    path('dashboard/employer/job<int:pk>/',EmployerJobDetail.as_view(),name="employer-detail"),
    path('u/<str:email>/',ProfileView.as_view(),name='profile'),
    path('u/<str:email>/edit/',ProfileEditView.as_view(),name='profile-edit'),
]

apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from .managers import CustomUserManager
from apps.job.models import Application
from django.dispatch import receiver
from django.db.models.signals import post_save

class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class UserProfile(models.Model):
    user = models.OneToOneField(CustomUser,related_name='profile',on_delete=models.CASCADE)
    is_employer = models.BooleanField(default=False)
    username = models.CharField(max_length=222,blank=True,null=True)
    field = models.CharField(max_length=30,blank=True,null=True)
    about = models.CharField(max_length=500,blank=True,null=True)
    country = models.CharField(max_length=120,blank=True,null=True)
    qualification = models.CharField(max_length=150,blank=True,null=True)
    age = models.PositiveIntegerField(blank=True,null=True)
    contact = models.CharField(max_length=222,blank=True, null=True)
    gender = models.CharField(max_length=30,blank=True,null=True)
    experience = models.CharField(max_length=222,blank=True, null=True)
    education = models.CharField(max_length=222,blank=True,null=True)
    status = models.BooleanField(default=True)
  
    def __str__(self):
        return self.username
    
class Conversation(models.Model):
    application = models.ForeignKey(Application,related_name="applicationconversation",on_delete=models.CASCADE)
    message = models.TextField()
    created_by = models.ForeignKey(CustomUser,related_name="applicationconversation",on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_on']
        
    def __str__(self):
        return str(self.application) + 'conversation'
    
    
    
@receiver(post_save, sender=CustomUser)
def update_user_profile(sender, instance, created, **kwargs):
    """
    Signals the Profile about User creation.
    """
    if created:
        UserProfile.objects.create(user=instance)
    instance.profile.save()
    
@receiver(post_save, sender=CustomUser)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, UserProfile


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)
        
class ProfileForm(forms.ModelForm):
    
    class Meta:
        model = UserProfile
        fields = ['username','field','about','age','qualification','country','contact','gender','experience','education','status']

apps/users/views.py
import profile
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View
from django.views.generic.base import RedirectView
from apps.job.models import Job, Application
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Conversation, UserProfile
from .forms import ProfileForm
from apps.notification.utilities import create_notification

class Dashboard(View,LoginRequiredMixin):
    def get(self,request):
        
        user = request.user
        applications = Application.objects.filter(created_by=user)
        your_jobs = Job.objects.filter(created_by=user).order_by('-created_on')
        applied_jobs = Job.objects.filter(application__created_by=user)
        
        context ={
            'applications': applications,
            'your_jobs': your_jobs,
            'user':request.user.profile,
            'applied_jobs': applied_jobs
        }
        return render(request,'user/dashboard.html', context)

class EmployerJobDetail(View, LoginRequiredMixin):
    def get(self,request,pk,*args,**kwargs):
        job = get_object_or_404(Job,pk=pk,created_by=request.user)
        
        return render(request,'user/get-job-detail.html',{'job':job})
    
    
class ApplicantJobDetail(View,LoginRequiredMixin):
    def get(self,request,pk,*args,**kwargs):
        if request.user.profile.is_employer:
            application = get_object_or_404(Application,pk=pk,job__created_by=request.user)
        else:
            application = get_object_or_404(Application,pk=pk,created_by=request.user)
        job = Job.objects.get(application=application)
        print(0)
        conversation_message = Conversation.objects.filter(application=application)
        
        context ={
            'job':job,
            'application':application,
            'messages':conversation_message
                  }
        return render(request,'user/get-application-detail.html',context)
    def post(self,request,pk,*args,**kwargs):
        if request.user.profile.is_employer:
            application = get_object_or_404(Application,pk=pk,job__created_by=request.user)
        else:
            application = get_object_or_404(Application,pk=pk,created_by=request.user)
        job = Job.objects.get(application=application)
        
        message = request.POST.get('message')
        if message:
            conversation_message = Conversation.objects.create(application=application,message=message,created_by=request.user)
            conversation_message.save()
            if conversation_message.created_by != application.created_by:
                notification_to = application.created_by
            else:
                notification_to = job.created_by
            create_notification(request, notification_to, 'message', application.pk)
        
        messages = Conversation.objects.filter(application=application)
            
        context ={
            'job':job,
            'application':application,
            'messages':messages
        }
        return render(request,'user/partials/message.html',context)
        
class ProfileView(View, LoginRequiredMixin):
    def get(self,request,email,*args,**kwargs):
        # profile = get_object_or_404(UserProfile,user__email=email)
        profile = UserProfile.objects.get(user__email=email)
        
        context ={
            'profile': profile,
        }
        return render(request,'user/profile.html',context)
    
class ProfileEditView(View):
    def get(self,request,email,*args,**kwargs):
        profile = get_object_or_404(UserProfile,user__email=request.user)
        context = {
            'profile': profile
        }
        return render(request,'user/profile-edit.html',context)
        
    def post(self,request,email,*args,**kwargs):
        profile = get_object_or_404(UserProfile,user__email=request.user)
        form = ProfileForm(request.POST,instance=profile)
        if profile:
            if form.is_valid():
                profile.save()
                
                return redirect('users:profile',request.user.email)
            return render(request,'user/profile.html',{'profile':profile})
        

apps/users/templates/user/get-job-detail.html
{% extends 'user/dashboard.html' %}
{% block title %}Details: {{job.title}} {% endblock title %}
{% block body %}
<div class="container m-12 p-5 text-gray-700 rounded-lg bg-gray-200 shadow px-5 py-24">
    <div class="mb-20 text-center">
        <p class="w-full p-4 m-6 rounded-lg font-semibold text-center bg-purple-600 text-white uppercase">Job Informations</p>
        
        <div class="">
            <h4 class="text-lg font-bold">Description:</h4>
            <p class="text-normal p-1 font-light text-center "> {{job.description }}</p>
        </div>
        <div class="">
            <h4 class="text-lg font-bold">Details:</h4>
            <p class="text-normal p-1 font-light text-center "> {{job.detail }}</p>
        </div>

        <p class="mx-auto mb-6 text-base leading-relaxed xl:w-2/4 lg:w-3/4">
            Here are details of the  <span class="border-b-4 uppercase border-purple-500">responses</span>
            from the job you posted.
        </p>
    </div>
    <div class="flex flex-wrap -mx-2 lg:w-4/5 sm:mx-auto sm:mb-2">
        <div class="w-full px-4 py-2 lg:w-1/2">
            <details class="mb-4 bg-gray-100">
                <summary class="px-4 py-2 font-semibold bg-gray-300 rounded-md cursor-pointer">
                    Job title:
                </summary>

                <p class="px-4 text-lg font-light text-gray-600 py-2">
                    {{job.title}}
                </p>
            </details>
            <details class="mb-4 bg-gray-100">
                <summary class="px-4 py-2 font-semibold bg-gray-300 rounded-md cursor-pointer">
                    Payment Range
                </summary>

                <p class="px-4 text-lg font-light text-gray-600 py-2">
                    {{job.payment_range}}
                </p>
            </details>
             <details class="mb-4 bg-gray-100">
                <summary class="px-4 py-2 font-semibold bg-gray-300 rounded-md cursor-pointer">
                    Wage
                </summary>

                <p class="px-4 text-lg font-light text-gray-600 py-2">
                    {{job.payment_range}}
                </p>
            </details>
            <details class="mb-4 bg-gray-100">
                <summary class="px-4 py-2 font-semibold bg-gray-300 rounded-md cursor-pointer">
                    Remote or On Site
                </summary>

                <p class="px-4 text-lg font-light text-gray-600 py-2">
                    {% if job.remote %}Remote {% else %} On Site {% endif %}
                </p>
            </details>
        </div>
        <div class="w-full px-4 py-2 lg:w-1/2">
            <details class="mb-4 bg-gray-100">
                <summary class="px-4 py-2 font-semibold bg-gray-300 rounded-md cursor-pointer">
                    Total Number of applicant(s)
                </summary>

                <p class="px-4 text-lg font-light text-gray-600  py-2">
                    {{job.application.count}}
                </p>
            </details>
            <details class="mb-4 bg-gray-100">
                <summary class="px-4 py-2 font-semibold bg-gray-300 rounded-md cursor-pointer">
                    Required Experience
                </summary>

                <p class="px-4 text-lg font-light text-gray-600 py-2">
                    {{job.experience}}
                </p>
            </details>
           
            <details class="mb-4 bg-gray-100">
                <summary class="px-4 py-2 font-semibold bg-gray-300 rounded-md cursor-pointer">
                    Job Duration
                </summary>

                <p class="px-4 text-lg font-light text-gray-600 py-2">
                    {{job.duration}}
                </p>
            </details>
        </div>
    </div>
    <div hx-boost="true" class="flex justify-center mt-8 space-x-3">
        <a href="{% url 'job:delete-job' job.pk%}" class="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-white bg-red-600 border border-transparent rounded-md shadow hover:bg-red-700">{%csrf_token%} Delete Job</a>
        <a href="{% url 'job:edit-job' job.pk %}" class="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-indigo-700 bg-indigo-100 border border-transparent rounded-md hover:bg-indigo-200">Edit Job
        </a>
    </div>
</div>
<p class="w-full p-4 m-6 rounded-lg font-semibold text-center bg-purple-600 text-white uppercase">Applicants Informations</p>
<section class="relative py-16 bg-white min-w-screen animation-fade animation-delay">
    <div class="container px-0 mx-auto sm:px-5">
        {% for application in job.application.all %}
            <div
                class="w-full relative px-6 py-6 mx-auto mt-10 bg-white border border-gray-200 sm:px-8 md:px-12 sm:py-8 sm:rounded-lg sm:shadow md:w-2/3">
                <h3 hx-boost="true" class="text-lg font-bold text-purple-500 sm:text-xl md:text-2xl">Applicant name: 
                <a href="{% url 'users:profile' application.created_by%}">{% if application.created_by.profile.username %}{{application.created_by.profile.username}}{% else %} {{application.created_by}}{% endif %} </a>
                </h3>
                 
                <small class="mx-6 text-xs font-bold text-left text-purple-500 uppercase sm:text-center sm:text-normal sm:font-bold">Applicants Experience: {{application.experience}}</small>
                <p class="mt-2 text-base text-gray-600 sm:text-lg md:text-normal">Proposal: {{application.proposal}}</p>
                 <a href="{% url 'users:applicant-detail' application.pk%}" class="absolute  bottom-0 h-16 py-3 text-center w-2/3 font-medium text-white bg-purple-700 border border-transparent rounded-md hover:bg-purple-500">View Application detail</a>
            </div>
        {% empty %}
            <p class="mt-2 text-base text-gray-600 sm:text-lg md:text-normal">No applicant for this job yet.</p>
        {% endfor %}
    </div>
</section>
{% endblock body %}

apps/users/templates/user/profile-edit.html
{% extends 'user/dashboard.html' %}
{% block title %}Profile Edit{% endblock title %}
{% block body %}
<div class="bg-gray-300">
    <div class="py-12">
        <div class="w-full bg-white shadow-lg rounded-lg mx-2">
            <div class="md:flex ">
                <div class="w-full p-4 px-5 py-5">
                    <span>Edit Profile</span>
                    <div class="relative pb-5"> 
                    <form method="POST" action="{% url 'users:profile-edit' profile.user %}">
                    {% csrf_token %}
                        <input type="text" {% if profile.username != None %}value="{{profile.username}}"{% endif %} class="name="username" class="border rounded h-10 w-full focus:outline-none focus:border-green-200 px-2 mt-2 text-sm" placeholder="Username"> 
                        <div class="grid md:grid-cols-2 md:gap-2"> 
                            <input type="text" {% if profile.field != None %}value="{{profile.field}}{% endif %}" name="field" class="border rounded h-10 w-full focus:outline-none focus:border-green-200 px-2 mt-2 text-sm" placeholder="Field*"> 
                            <input type="text" {% if profile.age != None  %}value="{{profile.age}}"{% endif %}  name="age" class="border rounded h-10 w-full focus:outline-none focus:border-green-200 px-2 mt-2 text-sm" placeholder="Age*"> 
                        </div> 
                        <input type="text" {% if profile.qualification != None %}value="{{profile.qualification}}"{% endif %}  name="qualification" class="border rounded h-10 w-full focus:outline-none focus:border-green-200 px-2 mt-2 text-sm" placeholder="Qualification"> 
                        <input type="text" {% if profile.experience != None %}value="{{profile.experience}}"{% endif %}  name="experience" class="border rounded h-10 w-full focus:outline-none focus:border-green-200 px-2 mt-2 text-sm" placeholder="Experience* (Specify if in years or months)"> 
                        <input type="text" {% if profile.education != None %} value="{{profile.education}}"{% endif %} name="education" class="border rounded h-10 w-full focus:outline-none focus:border-green-200 px-2 mt-2 text-sm" placeholder="Education">
                        <div class="grid md:grid-cols-3 md:gap-2"> 
                            <input type="text" {% if profile.country != None %}value="{{profile.country}}"{% endif %}  name="country" class="border rounded h-10 w-full focus:outline-none focus:border-green-200 px-2 mt-2 text-sm" placeholder="Country*"> 
                            <input type="text" {% if profile.contact != None %}value="{{profile.contact}}"{% endif %}  name="contact" class="border rounded h-10 w-full focus:outline-none focus:border-green-200 px-2 mt-2 text-sm" placeholder="Gender*"> 
                            <input type="text" {% if profile.gender != None %}value="{{profile.gender}}" {% endif %} name="gender" class="border rounded h-10 w-full focus:outline-none focus:border-green-200 px-2 mt-2 text-sm" placeholder="Contact*"> 
                        </div> 
                        <textarea name="about" {% if profile.about != None %}value="{{profile.about}}"{% endif %}  placeholder="About your self in just 500 words" class="border rounded h-20 w-full focus:outline-none focus:border-green-200 px-2 mt-2 text-sm"rows="3"></textarea>
                        <div class="flex justify-between items-center pt-2"> 
                            <button hx-boost="true" type="button"class="h-12 w-24 text-blue-500 text-xs font-medium"><a href="{% url 'users:profile' profile.user %}">Return to Profile</a></button> 
                            <button hx-boost="true" type="submit" class="h-12 w-48 rounded font-medium text-xs bg-blue-500 text-white">Save Changes</a></button> 
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

apps/users/templates/user/profile.html
{% extends 'user/dashboard.html' %}
{% block title %}Profile {% endblock title %}
{% block body %}

<div class="bg-gray-100">
 <div class="w-full text-white bg-main-color">
 
<div class="container mx-auto my-5 p-5">
    <div class="md:flex no-wrap md:-mx-2 ">
        <!-- Left Side -->
        <div class="w-full md:w-3/12 md:mx-2">
            <!-- Profile Card -->
            <div class="bg-white p-3 border-t-4 border-green-400">
                <div class="image overflow-hidden">
                    <img class="h-auto w-full mx-auto"
                        src="https://ui-avatars.com/api/?background=random&name={% if profile.username %}
                        {{profile.username}}
                    {% else %}
                        {{request.user.first_name}}
                    {% endif %}" alt="">
                </div>
                <h1 class="text-gray-900 font-bold text-xl leading-8 my-1">
                {% if profile.username %}
                    {{profile.username}}
                {% else %}
                    {{profile.user.email}}
                {% endif %}
                </h1>
                <h3 class="text-gray-600 font-lg text-semibold leading-6">{{profile.field}}</h3>
                <p class="text-sm text-gray-500 hover:text-gray-600 leading-6">{{profile.about}}</p>
                <ul
                    class="bg-gray-100 text-gray-600 hover:text-gray-700 hover:shadow py-2 px-3 mt-3 divide-y rounded shadow-sm">
                    <li class="flex items-center py-3">
                        <span>Status</span>
                        <span class="ml-auto"><span
                                class="bg-green-500 py-1 px-2 rounded text-white text-sm">
                            {% if profile.status %}Active {% else %} Deactivated {% endif %}</span>
                    </li>
                    <li class="py-3">
                        <span>Joined:</span>
                        <span class="block text-sm tracking-tighter">{{request.user.date_joined|timesince}} ago.</span>
                    </li>
                    {% if request.user == profile.user %}
                        <li class="flex items-center py-3">
                        <a href="{% url 'users:profile-edit' profile.user.email%}" class="bg-purple-500 py-1 px-2 rounded text-white text-sm">Edit Profile </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- End of profile card -->
        <div class="my-4"></div>
                
            </div>
        <!-- Right Side -->
        <div class="w-full md:w-9/12 mx-2 h-64">
            <!-- Profile tab -->
            <!-- About Section -->
            <div class="bg-white p-3 shadow-sm rounded-sm">
                <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8">
                    <span clas="text-green-500">
                        <svg class="h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                        </svg>
                    </span>
                    <span class="tracking-wide">About</span>
                </div>
                <div class="text-gray-700">
                    <div class="grid md:grid-cols-2 text-sm">
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Name</div>
                            <div class="px-4 py-2">{{profile.username}}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Email</div>
                            <div class="px-4 py-2">{{profile.user.email}}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Gender</div>
                            <div class="px-4 py-2">{{profile.gender}}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Contact On.</div>
                            <div class="px-4 py-2">{{profile.contact}}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Country</div>
                            <div class="px-4 py-2">{{profile.country}}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Address</div>
                            <div class="px-4 py-2">{{profile.address}}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Age</div>
                            <div class="px-4 py-2">{{profile.age}}</div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of about section -->

            <div class="my-4"></div>

            <!-- Experience and education -->
            <div class="bg-white p-3 shadow-sm rounded-sm">

                <div class="grid grid-cols-2">
                    <div>
                        <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8 mb-3">
                            <span clas="text-green-500">
                                <svg class="h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                </svg>
                            </span>
                            <span class="tracking-wide">Experience</span>
                        </div>
                        <ul class="list-inside space-y-2">
                            <li>
                                <div class="text-teal-600">{{profile.experience}}</div>
                                <div class="text-gray-500 text-xs">...........</div>
                            </li>
                    </div>
                    <div>
                        <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8 mb-3">
                            <span clas="text-green-500">
                                <svg class="h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path fill="#fff" d="M12 14l9-5-9-5-9 5 9 5z" />
                                    <path fill="#fff"
                                        d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222" />
                                </svg>
                            </span>
                            <span class="tracking-wide">Education</span>
                        </div>
                        <ul class="list-inside space-y-2">
                            <li>
                                <div class="text-teal-600">{{profile.education}}</div>
                                <div class="text-gray-500 text-xs">...........</div>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- End of Experience and education grid -->
            </div>
            <!-- End of profile tab -->
        </div>
    </div>
</div>
</div>
{%endblock body %}