FidehJobs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views


urlpatterns = [
    path('admin/for-management/of/this/domain/', admin.site.urls,name="management"),
    path('', include('apps.core.urls')),
    path('job/',include('apps.job.urls')),
    path('user/', include('apps.users.urls')),
    path('notification',include('apps.notification.urls')),
    path('accounts/password_reset/',views.PasswordResetView.as_view(template_name="password/password_reset.html"),name='password_reset'),
    path('user/password/reset/done/',views.PasswordResetDoneView.as_view(template_name="password/password_reset_done.html"),name='password_reset_done'),
    path('user/<uidb64>/password/<token>/confirm/',views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"),name='password_reset_confirm'),
    path('user/password/reset/success/',views.PasswordResetCompleteView.as_view(template_name="password/password_reset_complete.html"),name='password_reset_complete'),

    
]

apps/core/urls.py
from django.urls import path
from .views import LandingView, LoginView, SignUp,LogoutView,ContactView

app_name = 'core'
urlpatterns = [
    path('',LandingView.as_view(), name='landing'),
    path('login/',LoginView.as_view(),name='login'),
    path('sign-up/',SignUp.as_view(),name='signup'),
    path('log-out/',LogoutView.as_view(),name='logout'),
    path('contact/',ContactView.as_view(),name='contact')
]

apps/job/urls.py
from django.urls import path 
from .views import JobList, JobDetail,JobCreate,JobApplication,JobEdit,JobDelete,ApplicationDelete,JobSearch

app_name = 'job'
urlpatterns =[
    path('fideht/job<int:pk>/',JobDetail.as_view(),name='job-detail'),
    path('fideht/jobs/',JobList.as_view(),name='job-list'),
    path('fideht/job/create/',JobCreate.as_view(),name='create-job'),
    path('fideht/job/edit/<int:pk>/',JobEdit.as_view(),name='edit-job'),
    path('fideh/jobs/delete/<int:pk>/',JobDelete.as_view(),name='delete-job'),
    path('fideht/jobs/job<int:pk>/apply/',JobApplication.as_view(),name='job-apply'),
    path('fideht/job/application/<int:pk>/delete/',ApplicationDelete.as_view(),name='application-delete'),
    path('fideht/jobs/search/',JobSearch.as_view(),name='search'),
]

apps/users/urls.py
from django.urls import path
from .views import Dashboard, EmployerJobDetail, ApplicantJobDetail,ProfileView,ProfileEditView

app_name = 'users'
urlpatterns =[
    path('dashboard/',Dashboard.as_view(),name='dashboard'),
    path('dashboard/applicant/application<int:pk>/',ApplicantJobDetail.as_view(),name='applicant-detail'),
    path('dashboard/employer/job<int:pk>/',EmployerJobDetail.as_view(),name="employer-detail"),
    path('u/<str:email>/',ProfileView.as_view(),name='profile'),
    path('u/<str:email>/edit/',ProfileEditView.as_view(),name='profile-edit'),
]

apps/job/models.py
from django.db import models
from django.conf import settings

class Job(models.Model):
    title = models.CharField(max_length=223)
    description = models.TextField()
    detail = models.TextField(blank=True, null=True)
    duration = models.CharField(max_length=200,blank=True, null=True)
    payment_range = models.CharField(max_length=200,blank=True, null=True)
    remote = models.BooleanField(default=False,blank=True, null=True)
    experience = models.CharField(max_length=200,blank=True, null=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='jobs',on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    change_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
    
    
class Application(models.Model):
    job = models.ForeignKey(Job,related_name='application', on_delete=models.CASCADE)
    proposal = models.TextField()
    experience = models.TextField(blank=True, null=True)
    payment = models.CharField(max_length=222,blank=True, null=True)
    delivery = models.CharField(max_length=222,blank=True, null=True)
    
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='application',on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    

apps/job/forms.py
from django import forms
from .models import Job, Application

class JobCreateForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['title', 'description','detail','duration','payment_range','remote','experience']
        
class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['proposal','experience','payment','delivery']

apps/job/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View 
from django.urls import reverse_lazy
from django.db.models import Q
from django.core.paginator import Paginator
from .models import Job, Application
from .forms import JobCreateForm, ApplicationForm
from apps.notification.utilities import create_notification

class JobDetail(View,LoginRequiredMixin):
    def get(self, request,pk,*args,**kwargs):
        job = Job.objects.get(pk=pk)
        application = Application.objects.filter(job=job,created_by=request.user)
        context = {
            "job": job,
            'application':application,
        }
        return render(request,'job/job_detail.html',context)
    
class JobSearch(View,LoginRequiredMixin):
    def get(self, request):
        jobs = Job.objects.all().order_by('-created_on')
        page = Paginator(jobs,5)
        page_number = request.GET.get('page')
        page_obj = page.get_page(page_number)
        return render(request,'job/search.html',{'jobs':jobs,'page_obj':page_obj})
    
    def post(self,request):
        query = request.POST.get('query')
        remote = request.POST.get('remote')
        
        matching_jobs = Job.objects.filter(Q(title__icontains=query)| Q(description__icontains=query)|
                                           Q(detail__icontains=query)|Q(experience__icontains=query))
        remote_jobs = None
        if remote:
            remote_jobs = Job.objects.filter(remote=True and Q(title__icontains=query) | Q(description__icontains=query))
        context= {
            'jobs': matching_jobs,
            'remote': remote_jobs
        }
        return render(request,'job/partials/searchresult.html',context)
            

class JobList(View, LoginRequiredMixin):
    def get(self, request):
        jobs = Job.objects.all()
        
        context = {
            "jobs": jobs,
        }
        
        return render(request,'job/job-list.html',context)
    
class JobCreate(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self,request):
        return render(request,'job/create-job.html')
    
    def post(self, request, *args, **kwargs):
        user = request.user
        form = JobCreateForm(request.POST)
        remote = request.POST.get('remote_option')
        if form.is_valid():
            job = form.save(commit=False)
            job.created_by = user 
            if remote == 'remote':
                job.remote = True
            job.save()
            
            context= {
                'form':form
            }
            return HttpResponse('<p class="text-sm text-green-600 text-center">Succesfully added another job to your listing.</p>')
        else:
            return HttpResponse('<p class="text-sm text-red-600 text-center">*There is an error</p>')
        
    def test_func(self):
        return self.request.user.profile.is_employer == True
        
        
class JobEdit(LoginRequiredMixin,View):
    
    def get(self,request,pk):
        job = get_object_or_404(Job,pk=pk,created_by=request.user)
        return render(request,'job/edit-job.html',{'job':job})
    
    def post(self,request,pk,*args,**kwargs):
        job = get_object_or_404(Job,pk=pk,created_by=request.user)
        form = JobCreateForm(request.POST)
        remote = request.POST.get('remote_option')
        if form.is_valid():
            jobu = form.save(commit=False)
            if remote == 'remote':
                jobu.remote = True
            jobu.created_by = request.user
            jobu.save()
            
            return redirect('job:job-detail',pk=job.pk)
    
    
class JobDelete(LoginRequiredMixin,View):
    def get(self,request,pk,*args,**kwargs):
        job = get_object_or_404(Job,pk=pk,created_by=request.user)
        return render(request,'job/delete-job.html',{'job':job})
    def post(self,request,pk,*args,**kwargs):
        job = get_object_or_404(Job,pk=pk,created_by=request.user)
        job.delete()
        return redirect('users:dashboard')
    
    
        
class JobApplication(LoginRequiredMixin,UserPassesTestMixin,View):
    def get(self, request,pk,*args, **kwargs):
        job = Job.objects.get(pk=pk)
        application = Application.objects.filter(job=job,created_by=request.user)
        if application:
            return HttpResponse('<p class="text-sm text-red-600 text-center">You have applied for this job already</p>')
        context= {
                'job':job,
            }
        return render(request,'job/job-apply.html',context)
    
    def post(self,request,pk,*args,**kwargs):
        job = Job.objects.get(pk=pk)
        form = ApplicationForm(request.POST)
        applicants = Application.objects.filter(job=job)
        if request.user.profile.is_employer:
            return HttpResponse('<p class="text-sm text-red-600 text-center">An employer can not apply for jobs, sorry for any inconvenience caused.</p>')
        
        if request.user in applicants:
            return HttpResponse('<p class="text-sm text-red-600 text-center">"You have applied for this job before"</p>')
        if form.is_valid():
            application = form.save(commit=False)
            application.job = job
            application.created_by = request.user 
            application.save()
            
            create_notification(request, job.created_by, 'application', application.pk)
            
            return HttpResponse('<p class="text-sm text-green-600 text-center">*Application succesfully sent, creator would recieve notification.</p>')
            
        else:
            context= {
                'job':job,
                'form':form
            }
            return render(request,'job/job-apply.html',context)
    def test_func(self):
        if self.request.user.profile.is_employer:
            return False
        return True
    
class ApplicationDelete(View,LoginRequiredMixin):
    def get(self,request,pk):
        application = get_object_or_404(Application,pk=pk,created_by=request.user)
        return render(request,'job/application-delete.html',{'application': application})
    
    def post(self,request,pk,*args,**kwargs):
        application = get_object_or_404(Application,pk=pk,created_by=request.user)
        application.delete()
        return redirect('users:dashboard')

apps/job/templates/job/application-delete.html
{% extends 'user/dashboard.html' %}
{% block title %}Delete Applicantion {% endblock title %}
{% block body %}
<div class="">
        <div><h1 class="text-2xl m-10 mx-auto text-center">Are you sure you want to Delete?</h1>
        <p>{{application.proposal}}</p>
        </div>

        <div class="mt-8 flex justify-center">
            <div hx-boost="true" class="inline-flex rounded-md bg-blue-500 shadow">
                <form class="w-full justify-self-center" method="POST" action="{% url 'job:application-delete' application.pk%}">
                    {% csrf_token %}
                    <button class="justify-self-center" type="submit">
                        <h1 class="text-xl justify-self-center bg-purple-500 text-white p-4 hover:bg-purple-600 rounded pointer">Confirm Delete</h1>
                    </button>
                </form>
            </div>
        </div>
</div>

{% endblock body %}

apps/job/templates/job/create-job.html
{% extends 'user/dashboard.html' %}
{% block title %}Create Job{% endblock title %}
{% block body %}
<div class="bg-white mx-auto my-14 text-3xl font-bold p-14 rounded border-3 border-gray-200">
    <h5 class="text-2xl font-bold leading-normal text-center mt-0 mb-2 text-purple-800">
        Create New Job
      </h5>
    {% include 'job/partials/job-form.html' %}
    <div id="createjob"></div>
</div>

{% endblock body %}

apps/job/templates/job/delete-job.html
{% extends 'user/dashboard.html' %}
{% block title %}Delete Job{% endblock title %}
{% block body %}
<div class="">
        <div><h1 class="text-2xl m-10 mx-auto text-center">Are you sure you want to Delete {{job.title}}?</h1></div>

        <div class="mt-8 flex justify-center">
            <div hx-boost="true" class="inline-flex rounded-md bg-blue-500 shadow">
                <form class="w-full justify-self-center" method="POST" action="{% url 'job:delete-job' job.pk%}">
                    {% csrf_token %}
                    <button class="justify-self-center" type="submit">
                        <h1 class="text-xl justify-self-center bg-purple-500 text-white p-4 hover:bg-purple-600 rounded pointer">Confirm Delete</h1>
                    </button>
                </form>
            </div>
        </div>
</div>

{% endblock body %}

apps/job/templates/job/edit-job.html
{% extends 'user/dashboard.html' %}
{% block title %}Edit Job{% endblock title %}
{% block body %}
<div class="bg-white mx-auto my-14 text-3xl font-bold p-14 rounded border-3 border-gray-200">
    <h5 class="text-2xl font-bold leading-normal text-center mt-0 mb-2 text-purple-800">
        Edit Job
      </h5>
    <div hx-boost="true">
        <form action="{% url 'job:edit-job' job.pk%}" method="POST"class="space-y-4 p-8 text-gray-700">
            {% csrf_token %}
            <div class="mb-6">
            <label for="large-input" class="text-sm font-medium text-gray-900 block mb-2">Job Title</label>
            <input type="text" name="title" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-md rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-4">
        </div>
        <div class="mb-6">
            <label for="large-input" class="text-sm font-medium text-gray-900 block mb-2">Job Description</label>
            <textarea name="description" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-md rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-4" rows="3"></textarea>
        </div>
        <div class="mb-6">
            <label for="large-input" class="text-sm font-medium text-gray-900 block mb-2">Payment Range</label>
            <input type="text" name="payment_range" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-md rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-4">
        </div>
        
        <div class="grid md:grid-cols-2 md:gap-2"> 
             <select name="remote_option" class="block border border-grey-light w-full p-3 rounded mb-8" placeholder="Regular input">
                <option value="onsite" selected>On-site</option>
                <option value="remote">Remote</option>
            </select>
            <label for="large-input" class="text-sm font-medium text-gray-900 block mb-2">Duration</label>
            <input type="text" name="duration" placeholder="(in months or year)" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-md rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-4">
        </div>
        <div class="mb-6">
            <label for="large-input" class="text-sm font-medium text-gray-900 block mb-2">Job Detail</label>
            <textarea name="detail" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-md rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-4" rows="7"></textarea>
        </div>
            <div class="w-full flex-auto content-center bg-orange-500 rounded-lg m-2">
                <button type="submit" class="w-full h-12 px-6 text-white transition-colors duration-150 bg-purple-700 rounded-lg focus:shadow-outline hover:bg-purple-800">
                    Update Job
                </button>
            </div>
            {% if form.messages.error%}
            <p class="text-sm text-red-600 text-center">*{{messages.error}}</p>
            {% endif %}
            {% if form.messages.success%}
            <p class="text-sm text-green-600 text-center">*{{messages.error}}</p>
            {% endif %}
        </form>
    </div>
</div>

{% endblock body %}

apps/job/templates/job/job_detail.html
{% extends 'base.html' %}
{% block title %}Detail: {{job.title}} {% endblock title %}
{% block content %}
<div class="h-screen bg-gray-100 flex items-start lg:items-center justify-center">

<div class="container mx-auto px-3 md:px=4  h-full">
    <p class="w-full p-4 my-4 md:my-8 rounded-lg font-semibold self-center text-center bg-purple-600 text-white normal-case">Neccesary Informations about this Job.</p>
    <div class="self-center">
        <h3 class="text-xl text-purple-400 text-left p-1 font-semiboald ">Job Title: {{job.title}}</h3>
        <h3 hx-boost="true" class="text-xl text-left p-1  ">Job by: 
            <a href="{% url 'users:profile' job.created_by%}" class="font-semiboald cursor-pointer text-gray-700">{% if job.created_by.profile.username %}{{job.created_by.profile.username}} {% else %}{{job.created_by}}{% endif %}</a>  
        </h3>
    </div>
    <section x-data="{ selectedItem: 1 }" class="shadow-md bg-gray-200 overflow-hidden rounded-lg mt-6 sm:shadow-lg lg:mt-16 lg:mx-auto lg:max-w-4xl">
        
        <article class="border-gray-400 border-b hover:bg-gray-300">
            <div>
                <header @click="selectedItem === 3 ? selectedItem = 0 : selectedItem = 3" x-bind:class="{ 'bg-gray-300': selectedItem === 3 }" class="flex justify-between items-center p-5 pl-8 pr-8 cursor-pointer select-none">
                    <h3 class="font-semibold text-xl text-gray-800">
                        View Creation date
                    </h3>
                    <div class="rounded-full border w-7 h-7 flex items-center justify-center hover:bg-gray-200">
                        <div x-show="selectedItem !== 3" class="rounded-full text-gray-500 w-7 h-7 flex items-center justify-center">
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                        </div>
                        <div x-show="selectedItem === 3" class="rounded-full text-gray-500 w-7 h-7 flex items-center justify-center">
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                        </div>
                    </div>
                </header>
                <div x-show="selectedItem === 3">
                    <div class="pl-8 pr-8 py-5 bg-gray-100 text-gray-700">
                        <p>... {{job.created_on|timesince}} ago.</p>
                    </div>
                </div>
            </div>
        </article>
        
        <article class="border-gray-400 border-b hover:bg-gray-300">
            <div>
                <header @click="selectedItem === 1 ? selectedItem = 0 : selectedItem = 1" x-bind:class="{ 'bg-gray-300': selectedItem === 1 }" class="flex justify-between items-center p-5 pl-8 pr-8 cursor-pointer select-none">
                    <h3 class="font-semibold text-xl text-gray-800">
                        View Job Description
                    </h3>
                    <div class="rounded-full border w-7 h-7 flex items-center justify-center hover:bg-gray-200">
                        <div x-show="selectedItem !== 1" class="rounded-full text-gray-500 w-7 h-7 flex items-center justify-center">
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                        </div>
                        <div x-show="selectedItem === 1" class="rounded-full text-gray-500 w-7 h-7 flex items-center justify-center">
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                        </div>
                    </div>
                </header>
                <div x-show="selectedItem === 1">
                    <div class="pl-8 pr-8 py-5 bg-gray-100 text-gray-700">
                        <p>{{job.description}}</p>
                    </div>
                </div>
            </div>
        </article>

        <article class="border-gray-400 border-b hover:bg-gray-300">
            <div>
                <header @click="selectedItem === 2 ? selectedItem = 0 : selectedItem = 2" x-bind:class="{ 'bg-gray-300': selectedItem === 2 }" class="flex justify-between items-center p-5 pl-8 pr-8 cursor-pointer select-none">
                    <h3 class="font-semibold text-xl text-gray-800">
                        View Total Number of Applicants
                    </h3>
                    <div class="rounded-full border w-7 h-7 flex items-center justify-center hover:bg-gray-200">
                        <div x-show="selectedItem !== 2" class="rounded-full text-gray-500 w-7 h-7 flex items-center justify-center">
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                        </div>
                        <div x-show="selectedItem === 2" class="rounded-full text-gray-500 w-7 h-7 flex items-center justify-center">
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                        </div>
                    </div>
                </header>
                <div x-show="selectedItem === 2">
                    <div class="pl-8 pr-8 py-5 bg-gray-100 text-gray-700">
                        <p>{{job.application.count}} Applicants</p>
                    </div>
                </div>
            </div>
        </article>

        <article class="border-gray-400 border-b hover:bg-gray-300">
            <div>
                <header @click="selectedItem === 3 ? selectedItem = 0 : selectedItem = 3" x-bind:class="{ 'bg-gray-300': selectedItem === 3 }" class="flex justify-between items-center p-5 pl-8 pr-8 cursor-pointer select-none">
                    <h3 class="font-semibold text-xl text-gray-800">
                        View job details
                    </h3>
                    <div class="rounded-full border w-7 h-7 flex items-center justify-center hover:bg-gray-200">
                        <div x-show="selectedItem !== 3" class="rounded-full text-gray-500 w-7 h-7 flex items-center justify-center">
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                        </div>
                        <div x-show="selectedItem === 3" class="rounded-full text-gray-500 w-7 h-7 flex items-center justify-center">
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                        </div>
                    </div>
                </header>
                <div x-show="selectedItem === 3">
                    <div class="pl-8 pr-8 py-5 bg-gray-100 text-gray-700">
                        <p>{{job.detail}} </p>
                    </div>
                </div>
            </div>
        </article>
        <article class="border-gray-400 border-b hover:bg-gray-300">
            <div>
                <header @click="selectedItem === 3 ? selectedItem = 0 : selectedItem = 3" x-bind:class="{ 'bg-gray-300': selectedItem === 3 }" class="flex justify-between items-center p-5 pl-8 pr-8 cursor-pointer select-none">
                    <h3 class="font-semibold text-xl text-gray-800">
                        Job requirements: 
                    </h3>
                    <div class="rounded-full border w-7 h-7 flex items-center justify-center hover:bg-gray-200">
                        <div x-show="selectedItem !== 3" class="rounded-full text-gray-500 w-7 h-7 flex items-center justify-center">
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                        </div>
                        <div x-show="selectedItem === 3" class="rounded-full text-gray-500 w-7 h-7 flex items-center justify-center">
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                        </div>
                    </div>
                </header>
                <div x-show="selectedItem === 3">
                    <div class="pl-8 pr-8 py-5 bg-gray-100 text-gray-700">
                        <p>This employer has created {{job.created_by__job.count}} jobs</p>
                    </div>
                </div>
            </div>
        </article>
    </section>
    {% if application%}
    <div class="flex justify-center mt-8 space-x-3">
        <a 
            class="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-white bg-indigo-600 border border-transparent rounded-md shadow hover:bg-indigo-700">You have applied to this job already.</a>
    </div>
    {% else %}
        <section class=" bg-gray-200 rounded-lg mx-14 p-5 mt-5">
            <div class="px-4 mx-auto text-center max-w-7xl sm:px-6 lg:px-8">
                <p class="w-full p-4 pt-2 mb-3 md:mb-5 rounded-lg font-semibold text-center bg-purple-600 text-white normal-case">Job Application</p>

                <p class="max-w-md mx-auto mt-3 text-base text-gray-500 sm:text-lg md:mt-5 md:text-xl md:max-w-3xl">
                    Write a stand-out proposal that you feel would win you this job and present your experience to the employer for a consideration
                </p>
                {% if request.user.profile.is_employer %}
                <p class="max-w-md mx-auto mt-3 text-base text-gray-500 uppercase sm:text-lg md:mt-5 md:text-xl md:max-w-3xl">
                Employer users can not apply for jobs   
                </p>
                {% else %}
                <div class="flex justify-center mt-8 space-x-3">
                    <a 
                        {% if user.is_authenticated %}
                            href="{% url 'job:job-apply' job.pk %}" 
                        {% else %}
                            href="{% url 'core:login' %}"
                        {% endif %}
                        class="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-white bg-indigo-600 border border-transparent rounded-md shadow hover:bg-indigo-700">Apply</a>
                </div>
                {% endif %}
            </div>
        </section>
    {% endif %}
</div>
{% block footer %}{% endblock footer %}
{% endblock content %}