FidehJobs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views


urlpatterns = [
    path('admin/for-management/of/this/domain/', admin.site.urls,name="management"),
    path('', include('apps.core.urls')),
    path('job/',include('apps.job.urls')),
    path('user/', include('apps.users.urls')),
    path('notification',include('apps.notification.urls')),
    path('accounts/password_reset/',views.PasswordResetView.as_view(template_name="password/password_reset.html"),name='password_reset'),
    path('user/password/reset/done/',views.PasswordResetDoneView.as_view(template_name="password/password_reset_done.html"),name='password_reset_done'),
    path('user/<uidb64>/password/<token>/confirm/',views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"),name='password_reset_confirm'),
    path('user/password/reset/success/',views.PasswordResetCompleteView.as_view(template_name="password/password_reset_complete.html"),name='password_reset_complete'),

    
]

apps/core/urls.py
from django.urls import path
from .views import LandingView, LoginView, SignUp,LogoutView,ContactView

app_name = 'core'
urlpatterns = [
    path('',LandingView.as_view(), name='landing'),
    path('login/',LoginView.as_view(),name='login'),
    path('sign-up/',SignUp.as_view(),name='signup'),
    path('log-out/',LogoutView.as_view(),name='logout'),
    path('contact/',ContactView.as_view(),name='contact')
]

apps/notification/urls.py
from django.urls import path
from .views import NotificationListView

app_name = 'notification'
urlpatterns = [
    path('',NotificationListView.as_view(),name='notification')
]

apps/users/urls.py
from django.urls import path
from .views import Dashboard, EmployerJobDetail, ApplicantJobDetail,ProfileView,ProfileEditView

app_name = 'users'
urlpatterns =[
    path('dashboard/',Dashboard.as_view(),name='dashboard'),
    path('dashboard/applicant/application<int:pk>/',ApplicantJobDetail.as_view(),name='applicant-detail'),
    path('dashboard/employer/job<int:pk>/',EmployerJobDetail.as_view(),name="employer-detail"),
    path('u/<str:email>/',ProfileView.as_view(),name='profile'),
    path('u/<str:email>/edit/',ProfileEditView.as_view(),name='profile-edit'),
]

templates/base.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>{% block title %}{% endblock title %} | Fideht Jobs</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
        <script src="https://unpkg.com/htmx.org@1.6.1"></script>
        <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
        <script> document.body.addEventListener('configRequest.htmx', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';})
        </script>
	</head>
    <div class="container overflow-x-hidden">
    <body class="bg-gray-50 font-serif leading-normal tracking-normal" id="body">
        <div class="flex justify-between p-5 m-10 rounded-xl bg-gray-100 w-full">
            <div class="">
                <h1 hx-boost="true" class="text-2xl font-bold p-3 rounded-xl text-blue-400 font-large hover:bg-blue-100 hover:text-purple-700">
                    <a href="{% url 'core:landing' %}">FidehtJobs</a>
                </h1>
            </div>
            {% if user.is_authenticated %}
            <div class="block md:hidden">
                <li hx-boost="true" class="mx-3 text-bold uppercase text-purple-500 hover:text-white rounded-full hover:bg-purple-500 p-4 bg-white">
                    <a href="{% url 'users:dashboard' %}">Dashboard</a>
                </li>
            </div>
            {% endif %}
            <div class="block md:block">
                <ul class="flex justify-center items-center">
                {% block  nav-item %}
                {% if user.is_authenticated %}
                    <li class="mx-3 text-bold uppercase text-purple-500 hover:text-white rounded-full hover:bg-purple-500 p-4 bg-white">Home</li>
                    <li hx-boost="true" class="mx-3 text-bold uppercase text-purple-500 hover:text-white rounded-full hover:bg-purple-500 p-4 bg-white">
                        <a href="{% url 'users:dashboard' %}">Dashboard</a>
                    </li>
                    <li hx-boost="true" class="mx-3 text-bold uppercase text-purple-500 hover:text-white rounded-full hover:bg-purple-500 p-4 bg-white">
                        <a href="{% url 'notification:notification' %}">
                        <button class="rounded-full text-muted relative hover:bg-lightHover flex items-center justify-center p-3">
                            <svg class="w-6 h-6 hover:text-white" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 17H2a3 3 0 0 0 3-3V9a7 7 0 0 1 14 0v5a3 3 0 0 0 3 3zm-8.27 4a2 2 0 0 1-3.46 0"></path></svg>
                            <div class="rounded-full h-5 w-5 bg-red-600 text-white flex text-center justify-center absolute mb-5 ml-5 ">{{unread_notifications.count}}</div>
                        </button>
                        </a>
                    </li>
                    <li class="mx-3 text-bold uppercase text-purple-500 hover:text-white rounded-full hover:bg-purple-500 p-4 bg-white">contact</li>

                
                    <li class="mx-3 text-sm uppercase hover:text-purple-500 text-white rounded-xl bg-purple-500 p-4 hover:bg-white">
                        <a href="{% url 'core:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="mx-3 text-sm uppercase hover:text-purple-500 text-white rounded-xl bg-purple-500 p-4 hover:bg-white">
                        <a href="{% url 'core:login' %}">Login</a>
                    </li>
                    <li class="mx-3 text-sm uppercase hover:text-purple-500 text-white rounded-xl bg-purple-500 p-4 hover:bg-white">
                        <a href="{% url 'core:signup' %}">SignUp</a>
                    </li>
                {% endif %}
                {% endblock nav-item  %}
                
                </ul>
                
            </div>
        </div>
        <div class="">
        {% block content %}
        <div id="head"></div>
        
        {% endblock content %}
        
        </div>
        {% block footer %}{% include 'footer.html' %}{% endblock footer %}   
        
	</body>
    </div>
    
</html>

templates/contact.html
{% extends "base.html" %}
{% block title %}Contact Us{% endblock title %}
{% block content %}
<div class="flex flex-wrap py-8 border bg-gray-800 border-purple-100 text-center justify-center">
	<div class="w-full lg:w-6/12 px-4">
		<h2 class="text-4xl font-semibold text-pink-800">Get In-touch with us.</h2>
		<p class="text-lg leading-relaxed mt-4 mb-4 text-gray-300">
			You can reach us via our socialmedia handles or send us an email using the box below. We would love to hear from you, be it suggestions, reviews or requests.
		</p>
	</div>
</div>
<!-- component -->
<section id="contact" class="relative w-full min-h-screen bg-white dark:bg-gray-800 text-white">
<h1 class="text-4xl p-4 text-gray-800 font-bold tracking-wide">
    Contact:
</h1>
<div class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-pink-500 h-32 w-full"></div>

<!-- wrapper -->
<div class="relative p-5 lg:px-20 flex flex-col md:flex-row items-center justify-center">

    <!-- Social Media -->
    <div class="w-full md:w-1/2 p-5 md:px-0 mx-5">
    <div class="bg-gray-900 border border-pink- w-full lg:w-1/2 h-full p-5 pt-8">
        <h3 class="text-2xl font-semibold mb-5">Social Media</h3>
        <!-- list -->
        <div class="flex flex-col gap-3">
        <a href="https://twitter.com/heedngrow" class="flex items-center hover:text-white hover:bg-pink-500 p-2">
					<svg fill="currentColor" class="w-6 h-6 m-2" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
						<path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path>
					</svg>
            Twitter
        </a>
        <a href="#" class="flex items-center border-0 hover:text-white hover:bg-pink-500 p-2">
            <svg fill="currentColor" class="w-6 h-6 m-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" >
            <path d="M 21.800781 0 L 2.199219 0 C 1 0 0 1 0 2.199219 L 0 21.800781 C 0 23 1 24 2.199219 24 L 21.800781 24 C 23 24 24 23 24 21.800781 L 24 2.199219 C 24 1 23 0 21.800781 0 Z M 7 20 L 3 20 L 3 9 L 7 9 Z M 5 7.699219 C 3.800781 7.699219 3 6.898438 3 5.898438 C 3 4.800781 3.800781 4 5 4 C 6.199219 4 7 4.800781 7 5.800781 C 7 6.898438 6.199219 7.699219 5 7.699219 Z M 21 20 L 17 20 L 17 14 C 17 12.398438 15.898438 12 15.601563 12 C 15.300781 12 14 12.199219 14 14 C 14 14.199219 14 20 14 20 L 10 20 L 10 9 L 14 9 L 14 10.601563 C 14.601563 9.699219 15.601563 9 17.5 9 C 19.398438 9 21 10.5 21 14 Z"/>
            </svg>
            Linkedin
        </a>
        <a href="#" class="flex items-center hover:text-white hover:bg-pink-500 p-2">
            <svg fill="currentColor" class="w-6 h-6 m-2" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" >
            <path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"/>
            </svg>
            Youtube
        </a>
        <a href="https://web.facebook.com/heedngrow/" class="flex items-center hover:text-white hover:bg-pink-500 p-2">
            <svg fill="currentColor" class="w-6 h-6 m-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" >
            <path d="M12,0C5.373,0,0,5.373,0,12c0,6.016,4.432,10.984,10.206,11.852V15.18H7.237v-3.154h2.969V9.927c0-3.475,1.693-5,4.581-5 c1.383,0,2.115,0.103,2.461,0.149v2.753h-1.97c-1.226,0-1.654,1.163-1.654,2.473v1.724h3.593L16.73,15.18h-3.106v8.697 C19.481,23.083,24,18.075,24,12C24,5.373,18.627,0,12,0z"/>
            </svg>
            Facebook
        </a>
        <a href="https://web.instagram.com/heedngrow/" class="flex items-center hover:text-white hover:bg-pink-500 p-2">
            <svg class="w-6 h-6 m-2" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M3 15v4c0 1.1.9 2 2 2h14a2 2 0 0 0 2-2v-4M17 9l-5 5-5-5M12 12.8V2.5"/>
            </svg>
            Instagram
        </a>


        </div>
    </div>
    </div>
<!-- Contact Me -->
    <form hx-post="{% url 'contact'%}" hx-swap="innerHTML" hx-target="#contactus" class="w-full md:w-1/2 border border-pink-500 p-6 bg-gray-900">
    <h2 class="text-2xl pb-3 font-semibold">Send Message</h2>
    <div>
        <div class="flex flex-col mb-3">
            <label for="name">Name</label>
            <input type="text" id="name" name="name" class="px-3 py-2 bg-gray-800 border border-gray-900 focus:border-pink-500 focus:outline-none focus:bg-gray-800 focus:text-pink-500" autocomplete="off">
        </div>
        <div class="flex flex-col mb-3">
            <label for="email">Email</label>
            <input name="email" type="text" id="email" class="px-3 py-2 bg-gray-800 border border-gray-900 focus:border-pink-500 focus:outline-none focus:bg-gray-800 focus:text-pink-500" >
        </div>
        <div class="flex flex-col mb-3">
            <label for="message">Message</label>
            <textarea name="message" rows="4" id="message" class="px-3 py-2 bg-gray-800 border border-gray-900 focus:border-pink-500 focus:outline-none focus:bg-gray-800 focus:text-pink-500"></textarea>
        </div>
    </div>
    <div class="w-full pt-3">
        <button type="submit" class="w-full bg-gray-900 border border-pink-500 px-4 py-2 transition duration-50 focus:outline-none font-semibold hover:bg-pink-500 hover:text-white text-xl cursor-pointer">
        Send</button>
    </div>
        <div id="contactus"></div>
    </form>
</div>
</section>
{% endblock content %}

templates/footer.html
<footer class="bg-gray-800 dark:bg-gray-800 w-screen py-8">
    <div class="max-w-screen-xl mx-auto mt-20 px-4">
        <ul class="max-w-screen-md mx-auto text-lg font-light flex justify-between flex-wrap">
            <li class="my-2">
                <a class="text-gray-300 hover:text-gray-400 dark:text-gray-300 dark:hover:text-white transition-colors duration-200" href="https://www.linkedin.com/in/amusat-haki-07b35921b/" target="_blank">
                    Linkedin
                </a>
            </li>
            <li class="my-2">
                <a class="text-gray-300 hover:text-gray-400 dark:text-gray-300 dark:hover:text-white transition-colors duration-200" href="https://github.com/DeFidelity/Fideh-Jobs.git" target="_blank">
                    Github
                </a>
            </li>
            <li class="my-2">
                <a class="text-gray-300 hover:text-gray-400 dark:text-gray-300 dark:hover:text-white transition-colors duration-200" href="https://twitter.com/DeFidelity1" target="_blank">
                    Twitter
                </a>
            </li>
            <li class="my-2">
                <a class="text-gray-300 hover:text-gray-400 dark:text-gray-300 dark:hover:text-white transition-colors duration-200" href="{% url 'core:contact' %}">
                    Contact
                </a>
            </li>
        </ul>

            <div class="text-center text-gray-300 dark:text-gray-200 pt-10 sm:pt-12 font-light flex items-center justify-center">
                Fideht inc copyright 2021
            </div>
        </div>
    </footer>