FidehJobs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views


urlpatterns = [
    path('admin/for-management/of/this/domain/', admin.site.urls,name="management"),
    path('', include('apps.core.urls')),
    path('job/',include('apps.job.urls')),
    path('user/', include('apps.users.urls')),
    path('notification',include('apps.notification.urls')),
    path('accounts/password_reset/',views.PasswordResetView.as_view(template_name="password/password_reset.html"),name='password_reset'),
    path('user/password/reset/done/',views.PasswordResetDoneView.as_view(template_name="password/password_reset_done.html"),name='password_reset_done'),
    path('user/<uidb64>/password/<token>/confirm/',views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"),name='password_reset_confirm'),
    path('user/password/reset/success/',views.PasswordResetCompleteView.as_view(template_name="password/password_reset_complete.html"),name='password_reset_complete'),

    
]

apps/core/urls.py
from django.urls import path
from .views import LandingView, LoginView, SignUp,LogoutView,ContactView

app_name = 'core'
urlpatterns = [
    path('',LandingView.as_view(), name='landing'),
    path('login/',LoginView.as_view(),name='login'),
    path('sign-up/',SignUp.as_view(),name='signup'),
    path('log-out/',LogoutView.as_view(),name='logout'),
    path('contact/',ContactView.as_view(),name='contact')
]

apps/job/urls.py
from django.urls import path 
from .views import JobList, JobDetail,JobCreate,JobApplication,JobEdit,JobDelete,ApplicationDelete,JobSearch

app_name = 'job'
urlpatterns =[
    path('fideht/job<int:pk>/',JobDetail.as_view(),name='job-detail'),
    path('fideht/jobs/',JobList.as_view(),name='job-list'),
    path('fideht/job/create/',JobCreate.as_view(),name='create-job'),
    path('fideht/job/edit/<int:pk>/',JobEdit.as_view(),name='edit-job'),
    path('fideh/jobs/delete/<int:pk>/',JobDelete.as_view(),name='delete-job'),
    path('fideht/jobs/job<int:pk>/apply/',JobApplication.as_view(),name='job-apply'),
    path('fideht/job/application/<int:pk>/delete/',ApplicationDelete.as_view(),name='application-delete'),
    path('fideht/jobs/search/',JobSearch.as_view(),name='search'),
]

apps/core/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=100,blank=True)
    email = models.EmailField()
    message = models.TextField()
    date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return str(self.email)

apps/core/forms.py
from django import forms
from .models import Contact

class UserForm(forms.Form):
    first_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True)
    
class LoginForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True)
    first_name = forms.CharField(required=False)
    
class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name','email','message')

apps/core/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from apps.users.models import CustomUser
from django.contrib.auth import login, authenticate, logout
from django.views import View
from .forms import UserForm, LoginForm, ContactForm
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib import messages
from apps.job.models import Job


class LandingView(View):
    def get(self, request):
        jobs = Job.objects.all().order_by('-change_at')[0:3]
        return render(request,'core/landing.html',{'jobs': jobs})


class SignUp(UserPassesTestMixin,View):
    def get(self,request):
        return render(request,'core/signup.html')
    
    def post(self,request,*args, **kwargs):
        form = UserForm(request.POST)
        account_type = request.POST.get('user_type', 'jobseeker')
     
        if form.is_valid():
            email = request.POST.get('email')
            exists = CustomUser.objects.filter(email=email)
            if exists:
                messages.error(request,'We found an account for this email')
                # raise FormValidationError('we found an accout for this email')
            email = email
            password = request.POST.get('password')
            first_name = request.POST.get('first_name')
            user = CustomUser.objects.create_user(first_name=first_name, email=email, password=password)
            if account_type == 'employer':
                user.profile.is_employer = True
            user.save()
            login(request, user)
            return redirect('users:dashboard')
        else:
            messages.error(request,'Please fill all the forms correctly')
            return redirect('signup')
    def test_func(self):
        return not self.request.user.is_authenticated
    
class LoginView(UserPassesTestMixin,View):
    def get(self, request):
        return render(request,'core/login.html')
    
    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            email = request.POST.get('email')
            password = request.POST.get('password')
            auth = authenticate(email=email,password=password)
        
            if auth is not None:
                login(request, auth)
             
                return redirect('users:dashboard')
            
            else:
                messages.error(request,'Username or password not correct')
        
                return render(request,'core/login.html',{'form':form})
                
        else:
            messages.error(request,'Username or password not correct')
            return render(request,'core/login.html',{'form':form}) 
        
    def test_func(self):
        return not self.request.user.is_authenticated
        
class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request,'core/logout.html')
    
    def post(self,request):
        logout(request)
        return redirect('core:landing')
    
class ContactView(View):
    def get(self,request):
        return render(request,'contact.html')
    def post(self,request,*args, **kwargs):
        message = request.POST.get('message')
        form = ContactForm(request.POST)
        if len(message.split()) < 10:
            return HttpResponse('<p class="text-sm text-red-500 text-center">Form error,please write a descriptive message</p>')
            
        if form.is_valid():
            form.save()
            return HttpResponse('<p class="text-sm text-green-500 text-center">Thank you for reaching out to us, we will get back to you later</p>')
        else:
            return HttpResponse('<p class="text-sm text-red-500 text-center">Form error, please enter a valid email and descriptive message</p>')
            
            

apps/core/templates/core/landing.html
{% extends 'base.html' %}
{% block title %}Fideht Jobs {% endblock title %}
{% block content %}
    <div class="w-full h-full bg-white">
        <h1 class="text-bold text-gray-800 text-center uppercase my-12 text-xl">
            Welcome to fideh Jobs
            </h1>
        <div class="container relative max-w-2xl px-5 pt-12 mx-auto sm:py-12 lg:px-0">
            <h2
                class="mb-10 text-4xl font-extrabold leading-10 tracking-tight text-left text-gray-900 sm:text-5xl sm:leading-none md:text-6xl sm:text-center">
                Fideht <span class="inline-block text-indigo-500">Insiders</span></h2>
            <p class="mt-5 text-xl text-left opacity-75 sm:text-center">Our aim is to bring people together, help them collaborate on tools that can change the world. While we also link job seekers with potential employees. Make it happen.
            </p>
        </div>
        <div class="pb-1 text-center text-gray-700 bg-cover"> 
            <div class="my-8">
                <div class="max-w-xl px-4 mx-auto sm:px-6 lg:max-w-screen-xl lg:px-8">
                    <div class="lg:grid lg:grid-cols-3 gap-3 lg:gap-8 ">
                        {% for job in jobs %}
                            <div class="p-16 relative transition-all duration-150 border-2 border-gray-300 bg-white rounded-lg shadow-xl ease hover:shadow-2xl">
                                <h1 class="text-xl font-semibold text-left mt-4 p-3"> {{ job.title }}</h1>
                                <div class="">
                                    <p class="text-normal p-1 font-light text-center ">Desc: {{job.description|truncatewords:20 }}</p>
                                    {% comment %} <p class="text-sm font-thin mt-4 text-left">Detail {{job.detail|truncatewords:15}}.....</p> {% endcomment %}
                                </div>
                                <footer class="rounded-b-lg  text-sm text-gray-500 px-8 py-3 flex justify-between">
                                    <p class="m-3 text-md p-1">Created By:</p>
                                    <p class="m-3 p-1">{{job.created_by}}</p>
                                </footer>
                                <div class="text-center">
                                    <a class="absolute inset-x-0 bottom-0 h-16 mt-4 p-3 w-4/6 mx-auto bg-purple-500 text-white hover:bg-purple-800 rounded-lg shadow-xl"href="{% url 'job:job-detail' job.pk %}">View Job Details</a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    <h1 class="text-bold text-gray-800 bg-gray-200 text-center uppercase my-12 text-xl">Services </h1>

<div class="pb-1 text-center text-gray-700 bg-cover"> 
    <div class="my-8">
        <div class="max-w-xl px-4 mx-auto sm:px-6 lg:max-w-screen-xl lg:px-8">
            <div class="lg:grid lg:grid-cols-3 lg:gap-8">
                <div class="p-16 transition-all duration-150 bg-white rounded-lg shadow-xl ease hover:shadow-2xl">
                    <div
                        class="relative inline-flex items-center justify-center w-16 h-16 overflow-hidden text-white rounded-full">
                        <svg class="relative w-12 h-12 text-indigo-500" fill="none" stroke="currentColor"
                            viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M16 4v12l-4-2-4 2V4M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z">
                            </path>
                        </svg>
                    </div>
                    <div class="mt-3 mb-6">
                        <h5 class="pb-2 text-xl font-bold leading-6 text-gray-600">Listing</h5>
                        <p class="mt-1 text-base leading-6 text-gray-500">
                            List your job or apply to one it's all good.
                        </p>
                    </div>
                </div>
                <div
                    class="p-16 mt-10 transition-all duration-150 bg-white rounded-lg shadow-xl lg:mt-0 ease hover:shadow-2xl">
                    <div
                        class="relative inline-flex items-center justify-center w-16 h-16 overflow-hidden text-white rounded-full">
                        <svg class="relative w-12 h-12 text-indigo-500" fill="none" stroke="currentColor"
                            viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9">
                            </path>
                        </svg>
                    </div>
                    <div class="mt-3 mb-6">
                        <h5 class="pb-2 text-xl font-bold leading-6 text-gray-600">Notifications</h5>
                        <p class="mt-1 text-base leading-6 text-gray-500">
                            Automated notifications system that will keep your in the know.
                        </p>
                    </div>
                </div>
                <div
                    class="p-16 mt-10 transition-all duration-150 bg-white rounded-lg shadow-xl lg:mt-0 ease hover:shadow-2xl">
                    <div
                        class="relative inline-flex items-center justify-center w-16 h-16 overflow-hidden text-white rounded-full">
                        <svg class="relative w-12 h-12 text-indigo-500" fill="currentColor" viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M18 13V5a2 2 0 00-2-2H4a2 2 0 00-2 2v8a2 2 0 002 2h3l3 3 3-3h3a2 2 0 002-2zM5 7a1 1 0 011-1h8a1 1 0 110 2H6a1 1 0 01-1-1zm1 3a1 1 0 100 2h3a1 1 0 100-2H6z"
                                clip-rule="evenodd"></path>
                        </svg>
                    </div>
                    <div class="mt-3 mb-6">
                        <h5 class="pb-2 text-xl font-bold leading-6 text-gray-600">Messages</h5>
                        <p class="mt-1 text-base leading-6 text-gray-500">
                            A built-in message system to help you communicate and negotiate.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
        </div>
    </div>
</div>
{% endblock content %}

apps/core/templates/core/login.html
{% extends 'base.html' %}
{% block head %}Login {% endblock head %}
{% block nav-item %}{% endblock nav-item %}
{% block content %}

<div class="bg-grey-lighter min-h-screen flex flex-col">
    <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
        <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
        <p class="m-4 text-xl text-center uppercase text-light">Welcome <span class="">Back</span></p>
            <h1 class="mb-8 text-3xl text-center">Log In To Your Account</h1>
            <div hx-boost="true">
                <form method="POST" action="{% url 'core:login' %}">
                    {% csrf_token %}
                    <input 
                        type="text"
                        class="block border border-grey-light w-full p-3 rounded mb-4"
                        name="email"
                        placeholder="Email" />
                        {% for error in forms.email.errors %}
                            <p class="text-sm text-red-500 text-start">*{{error}}</p>
                        {% endfor %}
                    <input 
                        type="password"
                        class="block border border-grey-light w-full p-3 rounded mb-4"
                        name="password"
                        placeholder="Password" />
                        {% for error in forms.password.errors %}
                            <p class="text-sm text-red-500 text-start">*{{error}}</p>
                        {% endfor %}
                    <button
                        type="submit"
                        class="w-full text-center py-3 rounded bg-purple-500 text-white hover:bg-purple-900 focus:outline-none my-1"
                    >Login</button>
                </form>
            </div>
            {% if form.errors %}
                <p class="text-sm text-red-500 text-center">Your username and password didn't match. Please try again.</p>

            {% endif %}
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p>{{error}}</p>
                {% endfor %}
            {% endif %}
        </div>

        <div class="text-grey-dark mt-6" hx-boost="true">
            Forgotten password? 
            <a class="no-underline border-b border-blue text-blue" href="{% url 'password_reset' %}">
                reset password
            </a>.
        </div>
        <div class="text-grey-dark mt-6" hx-boost="true">
            Do not have an account? 
            <a class="underline border-b border-blue text-blue" href="{% url 'core:signup' %}">
                Sign up
            </a>.
        </div>
    </div>
</div>   
{% endblock content %}

apps/core/templates/core/logout.html
{% extends 'base.html' %}
{% block head %}Logout{% endblock head %}
{% block content %}

<div class="">
        <div><h1 class="text-2xl m-10 mx-auto text-center">Are you sure you want to Log-Out?</h1></div>

        <div class="mt-8 flex justify-center">
            <div hx-boost="true" class="inline-flex rounded-md bg-blue-500 shadow">
                <form class="w-full justify-self-center" method="POST" action="{% url 'core:logout' %}">
                    {% csrf_token %}
                    <button class="justify-self-center" type="submit">
                        <h1 class="text-xl justify-self-center bg-purple-500 text-white p-4 hover:bg-purple-600 rounded pointer">Log Me Out</h1>
                    </button>
                </form>
            </div>
        </div>
</div>


{% endblock content %}

apps/core/templates/core/signup.html
{% extends 'base.html' %}
{% block head %}Signup{% endblock head %}
{% block nav-item %}{% endblock nav-item %}
{% block content %}
<div class="bg-grey-lighter flex flex-col">
    <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
        <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
            <h1 class="mb-8 text-3xl text-center">Sign up</h1>
            
            {% include 'core/partials/signupform.html' %}

            {% if form.non_field_errors %}
            <p class="text-sm text-red-500 text-center">{{error}}</p>
            {% endif %}
        </div>

        <div class="text-grey-dark mt-6" hx-boost="true">
            Already have an account? 
            <a class="no-underline border-b border-blue text-blue" href="{% url 'core:login' %}">
                Log in
            </a>.
        </div>
    </div>
</div>    
{% endblock content %}